version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: library_db
    environment:
      MYSQL_ROOT_PASSWORD: pai3.1415926
      MYSQL_DATABASE: book_book_new_new
      MYSQL_USER: root
      MYSQL_PASSWORD: a123456.
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: